### ISSUE TITLE
Docker-compose config

### ISSUE THREAD

**Issue by opensorceror** [opensorceror/deepspeech-websocket-server#1]
Adding a docker-compose configuration to the repository would make it easier for users to get up and running with the server for development or production deployments.

Ideally, the docker-compose config would use the Dockerfile in this repo.

**Comment by azarezade** [comment]
@opensorceror you can use this `docker-compose.yml` file:

```
version: '3'

services:
  stts:
    build: .
    command: python -m deepspeech_server.app
    volumes:
      - ./deepspeech_server:/opt/deepspeech/deepspeech_server
      - ./application.conf:/opt/deepspeech/application.conf
    ports:
      - "8090:8080"
```
